### ISSUE TITLE
Google Analytics ua 값이 johngrib.github.io의 것을 사용하고 있습니다.

### ISSUE THREAD

**Issue by johngrib** [honggaruy/honggaruy.github.io#7]
안녕하세요. `UA-110224147-1`는 제 블로그가 예전에 사용했던 ua 값입니다. 홍가뤼님은 홍가뤼 님의 ua를 사용하시는 것이 좋을 것 같습니다.

https://github.com/honggaruy/honggaruy.github.io/blob/d4b7a6b7e369c8e3b94f062065a22c89fafeb5c2/_config.yml#L51-L52

![image](https://user-images.githubusercontent.com/1855714/125615702-99c52e66-1b44-4bdd-98a8-65c972848605.png)

이 값을 쓰고 계시기 때문에 제가 제 블로그의 통계를 보기 위해 google search console insights에 들어가면 홍가뤼님의 블로그에 대한 통계가 섞여서 보입니다.

![image](https://user-images.githubusercontent.com/1855714/125615859-cd533989-0f9a-48bb-a043-e52ba947d994.png)

**Comment by honggaruy** [comment]
늦게 봤습니다. 모르고 있었네요.  일단 코멘트처리로 수정하겠습니다.
불편을 끼쳐드려 죄송합니다.

**Comment by honggaruy** [comment]
~~위 수정사항으로 문제가 해결되었는지 알려주시면 이슈 close 하겠습니다.~~
github action을 걸어 놨는데 현재 fail중으로 변경사항이 반영되지 않습니다. 문제 해결후 업데이트 하겠습니다.

**Comment by honggaruy** [comment]
github action 에러 수정했고, 인터넷으로 배포된 사이트 접속시 `header.html`에서  `site.google_analytics.ua` 와 `site.google_adsense.client` 조건으로 나타나게 해놓은 부분이 제거되는 것 확인했습니다.

문제가 해결되었는지 알려주시면 이슈  close 하겠습니다. (직접 close 해주셔도 됩니다.)

**Comment by johngrib** [comment]
통계는 제가 확인할 수 있을 때까지는 적어도 며칠 정도는 걸릴 거에요. 코멘트처리하셨으니 작업이 잘 됐을 것 같네요. 이슈 클로즈할게요. 좋은 하루 보내세요.
